# [START yaml]
service: pub-sub-service
runtime: nodejs
env: flex
api_version: 1

# [START env]
env_variables:
  PUBSUB_TOPIC: home-hub-message
  PUBSUB_SUBSCRIPTION: home-hub-sub-update
  PUBSUB_VERIFICATION_TOKEN: AIzaSyCCqfwTxxlFbYMNja4THIj7UmIIxRNUgL0

# [END env]
# [END yaml]