version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
      - run: 
          name: Install build requirements
          command: sudo pip install -r portal/build-requirements.txt
      - run:
          name: Collectstatic
          command: sudo python portal/manage.py collectstatic --no-input
      - run:
          name: Set the cloud sdk env var
          command: export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
      - run:
          name: Add the Cloud SDK distribution URI as a package source
          command: echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      - run:
          name: Import public key
          command: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      - run:
          name: Install gcloud
          command: sudo apt-get update && sudo apt-get install google-cloud-sdk
      - run: |
          gcloud --quiet components update app
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project pwrnet-158117
          gcloud -q app deploy portal/app.yaml --promote --version=5 --log-http --verbosity=info        
          gsutil defacl set public-read gs://powernet-app-assets
          gsutil -m rsync -r portal/app/staticfiles gs://powernet-app-assets/
  
  
  # deploy:
  #   docker:
  #     - image: google/cloud-sdk
  #   steps:
  #     - run:
  #         name: Store Service Account
  #         command: echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
  #     - run: |
  #         gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
  #         gcloud --quiet config set project pwrnet-158117
  #         gcloud -q app deploy portal/app.yaml --promote --version=5 --log-http --verbosity=info        
  #         gsutil defacl set public-read gs://powernet-app-assets
  #         gsutil -m rsync -r portal/app/staticfiles gs://powernet-app-assets/

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master






# machine:
#   python:
#     version: 2.7.11

#   environment:
#     GCLOUD_PROJECT: "pwrnet-158117"

# dependencies:
#   pre:
#     # Download App Engine SDK
#     # This is not necessary to deploy, its only necessary  to run local tests importing the App Engine SDK
#     - curl -o $HOME/google_appengine_1.9.40.zip https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.40.zip
#     - unzip -q -d $HOME $HOME/google_appengine_1.9.40.zip

#     # Retrieve our secrets from the CircleCI environment
#     - echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json

#     # we install these reqs here so the rsync command down below passes    
#     - pip install -r portal/build-requirements.txt

#     # Make sure gcloud is up to date
#     - gcloud --quiet components update app

#     # authenticate gcloud
#     - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json

#     # Replace <your-project-id>
#     - gcloud config set project $GCLOUD_PROJECT

# test:
#   override:
#     # run local unit tests
#     - echo "test"

# deployment:
#     staging:
#         branch: master
#         commands:
#         # Collecstatic
#         - python portal/manage.py collectstatic --no-input
        
#         # deploy to AppEngine
#         - gcloud -q app deploy portal/app.yaml --promote --version=5 --log-http --verbosity=info        
#         - gsutil defacl set public-read gs://powernet-app-assets
#         - gsutil -m rsync -r portal/app/staticfiles gs://powernet-app-assets/