version: 2
jobs:
  build:
    # chosen path to do our build
    working_directory: ~/powernet
    docker:
      - image: circleci/python:3.7
    environment:
      DATABASE_PASSWORD: $DB_PASSWORD_JON
    steps:
      # git convenience method
      - checkout
      - run:
          name: Install python's build requirements
          command: |
            sudo pip install numpy
            sudo pip install -r portal/requirements.txt
      - run:
          name: Collect Static assets for later syncing with gcloud
          command: sudo python portal/manage.py collectstatic --no-input
      - run:
          name: Store gcloud Service Account Key
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode > portal/gcloud-service-key.json
      # persist the build we just made/verified
      - persist_to_workspace:
          root: .
          paths: portal/*

  deploy:
    # chosen path where we'll do our deploy from - same as build for convenience
    working_directory: ~/powernet
    docker:
      - image: google/cloud-sdk
    steps:
      # load the persisted workspace from the build job
      - attach_workspace:
          at: ~/powernet
      - run:
          name: Overwrite Secrets
          command: |
            sed -i "s/EGAUGE_USER=''/EGAUGE_USER='$EGAUGE_USER'/g" portal/app/settings/base.py
            sed -i "s/SONNEN_TOKEN=''/SONNEN_TOKEN='$SONNEN_TOKEN'/g" portal/app/settings/base.py
            sed -i "s/EGAUGE_PASSWORD=''/EGAUGE_PASSWORD='$EGAUGE_PASSWORD'/g" portal/app/settings/base.py
            sed -i "s/SUN_TECH_DRIVE_PASSWORD=''/SUN_TECH_DRIVE_PASSWORD='$SUN_TECH_DRIVE_PASSWORD'/g" portal/app/settings/base.py
            sed -i "s/SUN_TECH_DRIVE_USERNAME=''/SUN_TECH_DRIVE_USERNAME='$SUN_TECH_DRIVE_USERNAME'/g" portal/app/settings/base.py

      - run: |
          gcloud auth activate-service-account --key-file=portal/gcloud-service-key.json
          gcloud --quiet config set project pwrnet-158117
          gcloud config set app/cloud_build_timeout 1200
          gcloud -q app deploy portal/app.yaml --promote --version=15 --log-http --verbosity=info
          gsutil defacl set public-read gs://powernet-app-assets
          gsutil -m rsync -r portal/app/staticfiles gs://powernet-app-assets/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
