# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityEnergyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('timestamp_in_utc_millis', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'energy_price',
            },
        ),
    ]
