# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 22:38
from __future__ import unicode_literals

import app.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_device_devicestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=enumfields.fields.EnumField(default=b'UNKNOWN', enum=app.models.DeviceStatus, max_length=40),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=enumfields.fields.EnumField(enum=app.models.DeviceType, max_length=40),
        ),
    ]
