# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 20:03
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appliancejsondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HueStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', enumfields.fields.EnumField(default=b'UNKNOWN', enum=app.models.HueStatesType, max_length=40)),
            ],
            options={
                'db_table': 'hue_states',
            },
        ),
    ]
