# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_huestates'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
