# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_device_cosphi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cosphi',
            field=models.FloatField(default=1.0),
        ),
    ]
