# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-13 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180316_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Home'),
            preserve_default=False,
        ),
    ]
