# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-02 00:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_device_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatlabFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matlab_files',
            },
        ),
    ]
