# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-17 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_matlabfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliancejsondata',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Home'),
            preserve_default=False,
        ),
    ]
