# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-28 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_appliancejsondata_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatlabFiles',
        ),
    ]
