# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-27 23:21
from __future__ import unicode_literals

import app.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_matlabfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='powernetuser',
            name='type',
            field=enumfields.fields.EnumField(default=b'HOME', enum=app.models.PowernetUserType, max_length=10),
        ),
    ]
