# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-17 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_farmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmdevice',
            name='device_uid',
            field=models.CharField(default=b'UNKNOWN', max_length=100),
        ),
    ]
