# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-18 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_farmdevice_device_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmdevice',
            name='device_uid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='farmdevice',
            unique_together=set([('home', 'device_uid')]),
        ),
    ]
