# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-16 19:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190618_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmdevice',
            name='device_data',
        ),
        migrations.AlterModelTable(
            name='farmdevice',
            table='farm_device',
        ),
        migrations.CreateModel(
            name='FarmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'farm_device_data',
            },
        ),
        migrations.AddField(
            model_name='farmdata',
            name='farmdevice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FarmDevice'),
        ),
    ]
