# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-22 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190716_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmMaxDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_power', models.FloatField(default=0)),
                ('month_pst', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Home')),
            ],
            options={
                'db_table': 'farm_max_power_demand',
            },
        ),
    ]
