# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_farmmaxdemand'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcobeeDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('refresh_token', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ecobee',
            },
        ),
    ]
