# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip5', models.IntegerField()),
                ('TemperatureF', models.FloatField()),
                ('DewpointF', models.FloatField()),
                ('Pressure', models.FloatField()),
                ('WindSpeed', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('Clouds', models.CharField(max_length=10)),
                ('HourlyPrecip', models.FloatField()),
                ('SolarRadiation', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ResInterval60',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_id', models.BigIntegerField()),
                ('sa_id', models.BigIntegerField()),
                ('date', models.DateField()),
                ('date_char', models.CharField(max_length=10)),
                ('unitmeas', models.CharField(max_length=5)),
                ('q1', models.FloatField()),
                ('q2', models.FloatField()),
                ('q3', models.FloatField()),
                ('q4', models.FloatField()),
                ('q5', models.FloatField()),
                ('q6', models.FloatField()),
                ('q7', models.FloatField()),
                ('q8', models.FloatField()),
                ('q9', models.FloatField()),
                ('q10', models.FloatField()),
                ('q11', models.FloatField()),
                ('q12', models.FloatField()),
                ('q13', models.FloatField()),
                ('q14', models.FloatField()),
                ('q15', models.FloatField()),
                ('q16', models.FloatField()),
                ('q17', models.FloatField()),
                ('q18', models.FloatField()),
                ('q19', models.FloatField()),
                ('q20', models.FloatField()),
                ('q21', models.FloatField()),
                ('q22', models.FloatField()),
                ('q23', models.FloatField()),
                ('q24', models.FloatField()),
            ],
        ),
    ]
