runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT app.wsgi


handlers:
- url: /static
  static_dir: staticfiles/*
- url: .*
  script: app.wsgi.application

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 70
  timeout_sec: 10
  failure_threshold: 4
  success_threshold: 2

beta_settings:
  cloud_sql_instances: pwrnet-158117:us-central1:pwrnet-dev-store

env_variables:
  DEBUG: "False"