runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT app.wsgi

automatic_scaling:
  min_num_instances: 5
  max_num_instances: 15
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.5

handlers:
- url: /static
  static_dir: staticfiles/*
- url: .*
  script: app.wsgi.application

beta_settings:
  cloud_sql_instances: pwrnet-158117:us-central1:pwrnet-dev-store

env_variables:
  DEBUG: "False"
