runtime: python27
threadsafe: true
env: flex
entrypoint: gunicorn -b :$PORT app.wsgi

handlers:
- url: /static
  static_dir: staticfiles/*
- url: .*
  script: app.wsgi.application

beta_settings:
  cloud_sql_instances: pwrnet-158117:us-central1:pwrnet-dev-store

env_variables:
  DEBUG: "False"