runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT app.wsgi

resources:
  cpu: 8
  memory_gb: 2
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 6
  cool_down_period_sec: 100
  cpu_utilization:
    target_utilization: 0.6

handlers:
- url: /static
  static_dir: staticfiles/*
- url: .*
  script: app.wsgi.application

beta_settings:
  cloud_sql_instances: pwrnet-158117:us-central1:pwrnet-dev-store

env_variables:
  DEBUG: "False"
